/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Checkbox;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import models.FindListModel;
import models.TlbArtikliBezPopustModel;
import models.TlbNoviDodadeni;



/**
 *
 * @author petar
 */
public class ArtikliBezPopustView extends javax.swing.JFrame {
    
    public TlbArtikliBezPopustModel tlbArtikliBezPopustModel1;
    public FindListModel findModel1;  
            
    /**
     * Creates new form ArtikliBezPopustView
     * @param tblartiklibezpopustmodel
     * @param findmodel
     * @param tlbNoviDodadeni
    */
    public ArtikliBezPopustView(TlbArtikliBezPopustModel tblartiklibezpopustmodel,  
            FindListModel findmodel, TlbNoviDodadeni tlbNoviDodadeni)
    {
        initComponents();
        this.findModel1 = findmodel;                
        tblShowItem.setModel(tblartiklibezpopustmodel);
        tlbArtikliSmeneti.setModel(tlbNoviDodadeni);
    }
    
    public String gettxtSearch()
    {
        return txtSearch.getText();
    }
    
    public void setlblNaziv(String lbltext)
    {
       lblNazivArtikal.setText(lbltext);
    }
    
    public void setlblNazivClear()
    {
       lblNazivArtikal.setText(" ");
    }
    
    public JTable gettblArtikliSmeneti()
    {
        return tlbArtikliSmeneti;    
    }
    
    public JTable gettblShowItem()
    {
        return tblShowItem;
    }
    
    public void txtSearchEnter(ActionListener e)
    {
        txtSearch.addActionListener(e);
    }
    
    public void btnSearch(ActionListener evt) 
    { 
        btnSearch.addActionListener(evt);
    }

    
    public void btnGenerirajArtikli(ActionListener evt)
    {
        btnGenerirajArtikli.addActionListener(evt);
    }
    
    public void btnSave(ActionListener evt)
    {
        btnSave.addActionListener(evt);
    }
   
    
    public void tblShowItem(ListSelectionListener evt) 
    {
        tblShowItem.getSelectionModel().addListSelectionListener(evt);
        tblShowItem.repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbArtikliSmeneti = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblShowItem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblNazivArtikal = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chboxAllObject = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        chbox1 = new javax.swing.JCheckBox();
        chbox2 = new javax.swing.JCheckBox();
        chbox3 = new javax.swing.JCheckBox();
        chbox4 = new javax.swing.JCheckBox();
        chbox5 = new javax.swing.JCheckBox();
        chbox6 = new javax.swing.JCheckBox();
        chbox7 = new javax.swing.JCheckBox();
        chbox8 = new javax.swing.JCheckBox();
        chbox9 = new javax.swing.JCheckBox();
        chbox10 = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        lblSifraBarkod = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnGenerirajArtikli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jLabel2.setText("Последна промена");

        tlbArtikliSmeneti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tlbArtikliSmeneti.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tlbArtikliSmeneti);
        tlbArtikliSmeneti.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblShowItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblShowItem.setCellSelectionEnabled(true);
        tblShowItem.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(tblShowItem);
        tblShowItem.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblNaziv.setText("Naziv na artikal");

        jLabel1.setText("Датум од");

        jLabel3.setText("Датум до");

        chboxAllObject.setText("Сите објекти");
        chboxAllObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboxAllObjectActionPerformed(evt);
            }
        });

        jLabel4.setText("Објекти");

        chbox1.setText("СП 1");

        chbox2.setText("СП 2");

        chbox3.setText("СП 3");

        chbox4.setText("СП 4");

        chbox5.setText("СП 5");

        chbox6.setText("СП 6");

        chbox7.setText("СП 7");

        chbox8.setText("СП 8");

        chbox9.setText("СП 9");

        chbox10.setText("СП 10");

        btnSave.setText("Потврди");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(chbox9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbox2)
                            .addComponent(chbox4)
                            .addComponent(chbox6)
                            .addComponent(chbox8)
                            .addComponent(chbox10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNazivArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNaziv))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(chboxAllObject)
                            .addComponent(chbox1)
                            .addComponent(chbox3)
                            .addComponent(chbox5)
                            .addComponent(chbox7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblNaziv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNazivArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(chboxAllObject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbox1)
                            .addComponent(chbox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbox3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbox4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbox5)
                            .addComponent(chbox6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbox7)
                            .addComponent(chbox8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbox9)
                    .addComponent(chbox10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSifraBarkod.setText("Внеси Шифра");

        btnSearch.setText("Пребарај");

        btnGenerirajArtikli.setText("Генерирај артикли");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSifraBarkod, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnGenerirajArtikli)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraBarkod)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerirajArtikli)
                .addGap(392, 392, 392))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chboxAllObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboxAllObjectActionPerformed
        
        if(chboxAllObject.isSelected() == true)
        {
            chbox1.setSelected(true);
            chbox2.setSelected(true);
            chbox3.setSelected(true);
            chbox4.setSelected(true);
            chbox5.setSelected(true);
            chbox6.setSelected(true);
            chbox7.setSelected(true);
            chbox8.setSelected(true);
            chbox9.setSelected(true);
            chbox10.setSelected(true); 
        } 
        else 
        {
            chbox1.setSelected(false);
            chbox2.setSelected(false);
            chbox3.setSelected(false);
            chbox4.setSelected(false);
            chbox5.setSelected(false);
            chbox6.setSelected(false);
            chbox7.setSelected(false);
            chbox8.setSelected(false);
            chbox9.setSelected(false);
            chbox10.setSelected(false);
        }
        
    }//GEN-LAST:event_chboxAllObjectActionPerformed

    /**
     * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerirajArtikli;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox chbox1;
    private javax.swing.JCheckBox chbox10;
    private javax.swing.JCheckBox chbox2;
    private javax.swing.JCheckBox chbox3;
    private javax.swing.JCheckBox chbox4;
    private javax.swing.JCheckBox chbox5;
    private javax.swing.JCheckBox chbox6;
    private javax.swing.JCheckBox chbox7;
    private javax.swing.JCheckBox chbox8;
    private javax.swing.JCheckBox chbox9;
    private javax.swing.JCheckBox chboxAllObject;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNazivArtikal;
    private javax.swing.JLabel lblSifraBarkod;
    private javax.swing.JTable tblShowItem;
    private javax.swing.JTable tlbArtikliSmeneti;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
